/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jhl' at '16-3-14 下午7:19' with Gradle 2.10
 *
 * @author jhl, @date 16-3-14 下午7:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
